name: pokemon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - torchvision
  - pytorch
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - poke-env
      - pyyaml
      - tqdm
      - wandb